apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: local-ksox-finance

resources:
  - ./certificates.yaml
  - ./issuer.yaml
  - ./ksox-finance.yaml

generatorOptions:
  disableNameSuffixHash: true
