apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ksox.finance
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
    - hosts:
        - ksox.finance
      secretName: ksox-finance-tls
  rules:
    - host: ksox.finance
      http:
        paths:
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: ksox.finance
                port:
                  number: 80
