apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ksox-finance

resources:
  - ./../../resources
  - ./ksox-landing.yaml

secretGenerator:
  - name: ksox-landing-secrets
    env: ./enviroment/ksox-landing-secrets.env

configMapGenerator:
  - name: ksox-landing-config
    env: ./enviroment/ksox-landing-config.env

generatorOptions:
  disableNameSuffixHash: true
