name: Development Dynamic Enviroment

on:
  push:
    branches: ["development"]
  pull_request:
    branches: ["development"]

jobs:
  checkout:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

  kubeconfig:
    runs-on: self-hosted
    needs: ["checkout"]

    steps:
      - name: Create kubeconfig
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        run: |
          mkdir -p $GITHUB_WORKSPACE/.kube 
          echo "$KUBE_CONFIG" | base64 --decode > $GITHUB_WORKSPACE/.kube/config

  fmt:
    runs-on: self-hosted
    needs: ["kubeconfig"]

    steps:
      - name: Deploy to kubernetes
        run: skaffold run --kubeconfig "$GITHUB_WORKSPACE/.kube/config" --filename "$GITHUB_WORKSPACE/dev-skaffold.yaml" --default-repo registry.internal.visoft.solutions
