name: Dynamic Enviroment

on:
  push:
    branches: ["development"]
  pull_request:
    branches: ["development"]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Create kubeconfig
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        run: |
          mkdir -p $GITHUB_WORKSPACE/.kube 
          echo "$KUBE_CONFIG" | base64 --decode > $GITHUB_WORKSPACE/.kube/config
          export KUBECONFIG="$GITHUB_WORKSPACE/.kube/config"

      - name: Deploy to K8s
        run: kubectl --kubeconfig="$KUBECONFIG" get nodes