name: Master build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    strategy:
      matrix:
        runner: [arc-runner-set]

    runs-on: ${{ matrix.runner }}
    container: docker.io/node:lts-slim

    steps:
      - uses: actions/checkout@v4
      - name: install
        run: npm ci
      - name: fmt
        run: npm run fmt.check
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build