name: Master build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  checkout:
    runs-on: arc-runner-set

    steps:
      - uses: actions/checkout@v4

  install:
    runs-on: arc-runner-set
    needs: ["checkout"]

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci

  fmt:
    runs-on: arc-runner-set
    needs: ["install"]

    steps:
      - run: npm run fmt.check

  lint:
    runs-on: arc-runner-set
    needs: ["install"]

    steps:
      - run: npm run lint

  build:
    runs-on: arc-runner-set
    needs: ["install", "fmt", "lint"]

    steps:
      - run: npm run build
