name: Qwik build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  install:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci

  fmt:
    runs-on: self-hosted
    needs: ["install"]

    steps:
      - run: npm run fmt.check

  lint:
    runs-on: self-hosted
    needs: ["install"]

    steps:
      - run: npm run lint

  build:
    runs-on: self-hosted
    needs: ["install", "fmt", "lint"]

    steps:
      - run: npm run build
